//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.ServiceCobertura {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cobertura", Namespace="http://schemas.datacontract.org/2004/07/ProjetoSeguroWCF.TO")]
    [System.SerializableAttribute()]
    public partial class Cobertura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCoberturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCobertura {
            get {
                return this.IdCoberturaField;
            }
            set {
                if ((this.IdCoberturaField.Equals(value) != true)) {
                    this.IdCoberturaField = value;
                    this.RaisePropertyChanged("IdCobertura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCobertura.ICoberturaService")]
    public interface ICoberturaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoberturaService/ListCoberturas", ReplyAction="http://tempuri.org/ICoberturaService/ListCoberturasResponse")]
        Negocio.ServiceCobertura.Cobertura[] ListCoberturas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoberturaService/ListCoberturas", ReplyAction="http://tempuri.org/ICoberturaService/ListCoberturasResponse")]
        System.Threading.Tasks.Task<Negocio.ServiceCobertura.Cobertura[]> ListCoberturasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoberturaServiceChannel : Negocio.ServiceCobertura.ICoberturaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoberturaServiceClient : System.ServiceModel.ClientBase<Negocio.ServiceCobertura.ICoberturaService>, Negocio.ServiceCobertura.ICoberturaService {
        
        public CoberturaServiceClient() {
        }
        
        public CoberturaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoberturaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoberturaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoberturaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Negocio.ServiceCobertura.Cobertura[] ListCoberturas() {
            return base.Channel.ListCoberturas();
        }
        
        public System.Threading.Tasks.Task<Negocio.ServiceCobertura.Cobertura[]> ListCoberturasAsync() {
            return base.Channel.ListCoberturasAsync();
        }
    }
}
